import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { PlayComponent } from '@src/app/play/play.component';
import { CommonModule } from '@angular/common';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

@NgModule({
	declarations: [AppComponent, PlayComponent, AutoGeneratedComponent],
	imports: [BrowserModule, AppRoutingModule, CommonModule],
	providers: [],
	bootstrap: [AppComponent],
})
export class AppModule {}
